### ISSUE TITLE
Button styled as link text underline does not wrap with text

### ISSUE THREAD

**Issue by github-tma8118** [Legal-and-General/canopy#1109] opened 2022-12-12 09:09 UTC
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

When using a [button styled as a link](https://legal-and-general.github.io/canopy/?path=/story/components-button-examples--link) and the button text is very long, the text underline does not wrap neatly with the text.  The hover state underline also does not wrap with the text.

This bug affects:

* [ ] GitHub workflows
* [ ] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Visit Canopy's Storybook [button styled as a link example](https://legal-and-general.github.io/canopy/?path=/story/components-button-examples--link)
2. Modify the button text to be something long enough to wrap on the page (or use the browser dev tools to reduce the page width significantly enough to make it wrap)
3. Observe that the text and hover underlines are drawn as a single line at the bottom as if it was a button, and does not wrap neatly with the text

<img width="1017" alt="Screenshot 2022-12-12 at 09 07 53" src="https://user-images.githubusercontent.com/109232127/207005748-558f656b-2815-4382-a08e-47bc96b5ab19.png">

#### Expected behaviour:

Text and hover underlines wrap neatly with the text

<img width="291" alt="Screenshot 2022-12-12 at 08 56 39" src="https://user-images.githubusercontent.com/109232127/207003201-c763b4b9-1be6-48b6-bbde-10285ccc4479.png">

#### Actual behaviour:

Underline does not wrap neatly with the text

<img width="289" alt="Screenshot 2022-12-12 at 09 00 05" src="https://user-images.githubusercontent.com/109232127/207003981-50bf8ec6-85e0-4247-8168-0df080348b64.png">

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [ ] This problem started happening a while ago
* [x] Unsure

## Configuration and environment

* [ ] This pertains to **local development**
* [ ] This pertains to **the CI**
* [ ] This pertains to **Storybook**

## Additional Information

I modified the CSS for my FAQs card with the following rules, which produce the result shown in the expected behaviour above, but I obviously don't want to be putting these overrides in my app's CSS permanently:

```css
button {
  border-bottom: 0 !important;
  text-align: left;
  text-decoration: underline !important;

  &:hover,
  &:hover:visited {
    box-shadow: inset 0 3px 0 0 transparent, 0 0.188rem 0 0 transparent !important;
    text-decoration-thickness: 3px !important;
  }
}
```

**Comment by alexcanning** [comment] 2023-03-21 09:45
As I understand it, this is a limitation of the way we have chosen to style links (by design). Buttons styled as links isn't something we want to promote widespread usage of and it should only be used in a very specific case where a link needs to look like a link but has to be a button underneath. As such, I think this bug won't be fixed, but propose updating the documentation as follows:

1. Add guidance around the limited use of buttons styled as links
2. Add guidance around limited the length of a label for buttons styled as links

**Closed by alexcanning** 2023-03-21 09:45 UTC
