### ISSUE TITLE
Voice over - Not announcing when button is loading

### ISSUE THREAD

**Issue by ciprianandrusca** [Legal-and-General/canopy#1208] opened 2023-07-07 09:07 UTC
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] GitHub workflows
* [X] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Add a button element
2. Add 'loading' input to the button
3. Click the button one time
4. Click the button one more time after button is not loading anymore

#### Expected behaviour:

VO is announcing that the button is loading.

#### Actual behaviour:

VO is not announcing that the button is loading after the second click.

#### Recurrence frequency:

* [X] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [ ] This problem started happening a while ago
* [X] Unsure

## Configuration and environment

* [X] This pertains to **local development**
* [ ] This pertains to **the CI**
* [X] This pertains to **Storybook**

**Comment by elenagarrone** [comment] 2023-07-24 08:26
Hey,
Could you clarify why you'd want the `loading` to be read when clicking the button? At the moment it reads it when it starts loading it. The button is disabled when loading.

Has this been flagged by an audit?

**Comment by pauleustice** [comment] 2024-03-18 10:47
Closing this down as the actual behaviour sounds correct. Why would VoiceOver read that the button was loading when step 4 of the reproduction steps explicitly states that the button is not loading at the point of the second click?

As there's been no further updates on this ticket since July, I'm closing it down.

**Closed** 2024-03-18 11:11 UTC
Labels: bug
